### ISSUE TITLE
Error from decompressing file results in invalid status code on API

### ISSUE THREAD

**Issue by daschi** [Recidiviz/pulse-dashboard#894]
**Describe the bug**
There's an error being thrown and not handled properly in the API when there's an issue with processing the optimized metric file. I found this bug while trying to copy a file from production to staging, and probably copying it as the wrong file type (not exactly sure what was causing the error). The unhandled error is resulting in an [ERR_HTTP_INVALID_STATUS_CODE] being sent from the server because of how we are parsing errors for status code numbers.

The error sent to the responder:
```
Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (zlib.js:182:17)
    at Zlib.callbackTrampoline (internal/async_hooks.js:126:14) {
  errno: -3,
  code: 'Z_DATA_ERROR'
}
```

The error from the API server:
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: Z_DATA_ERROR
    at ServerResponse.writeHead (_http_server.js:248:11)
    at ServerResponse.writeHead (/Users/daschi/Desktop/Recidiviz/pulse-dashboard/node_modules/on-headers/index.js:44:26)
    at ServerResponse._implicitHeader (_http_server.js:239:8)
    at write_ (_http_outgoing.js:654:9)
    at ServerResponse.end (_http_outgoing.js:766:5)
    at ServerResponse.send (/Users/daschi/Desktop/Recidiviz/pulse-dashboard/node_modules/express/lib/response.js:221:10)
    at ServerResponse.json (/Users/daschi/Desktop/Recidiviz/pulse-dashboard/node_modules/express/lib/response.js:267:15)
    at ServerResponse.send (/Users/daschi/Desktop/Recidiviz/pulse-dashboard/node_modules/express/lib/response.js:158:21)
    at /Users/daschi/Desktop/Recidiviz/pulse-dashboard/server/routes/api.js:51:26
    at /Users/daschi/Desktop/Recidiviz/pulse-dashboard/server/core/cacheManager.js:101:9 {
  code: 'ERR_HTTP_INVALID_STATUS_CODE'
}

```

**To Reproduce**
1. Copy an incorrectly formatted `txt` metric file into the staging data bucket
2. Hit the API for that file
3. See the unhandled promise rejection / error

**Expected behavior**
Expect the error to return a valid status code to the HTTP responder

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]: 
 - Browser [e.g. chrome, edge]: 
 - Version [e.g. 22]: 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: 
 - OS: [e.g. iOS8.1]: 
 - Browser [e.g. stock browser, safari]: 
 - Version [e.g. 22]: 

**Additional context**

**Comment by daschi** [comment]
This PR removes the decompression function since it wasn't being used: https://github.com/Recidiviz/pulse-dashboard/pull/926
